version: '3'
services:
  app:
    build:
      context: .
# =========ローカルと本番切り替え===========
    command: bundle exec puma -C config/puma.rb -e production
    # command: bundle exec puma -C config/puma.rb
# ======================================
    volumes:
      - .:/smd
      - public-data:/smd/public
      - tmp-data:/smd/tmp
      - log-data:/smd/log
    networks:
      - smd-network
# =========ローカルと本番切り替え===========
  #   depends_on:
  #     - db

  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #     MYSQL_DATABASE: smd_development
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   networks:
  #     - smd-network
# ======================================

  web:
    build:
      context: ./containers
    volumes:
      - public-data:/smd/public
      - tmp-data:/smd/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - smd-network
volumes:
  public-data:

  tmp-data:
  log-data:
  db-data:

networks:
  smd-network:
    external: true
